name: quay-image

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - main

jobs:
  build:
    env:
      context: quay-image
      image_name: quay-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get image tags
        id: image_tags
        run: |
          VERSION=$(jq -r '.version' ${context}/version.json)
          TAGS=('latest')
          if [ "${VERSION}" ] && [ "${VERSION}" != "latest" ]; then
              TAGS+=("${VERSION}")
          fi
          if [[ "${GITHUB_REF}" =~ refs/tags/(.*) ]]; then
              TAGS+=("git-${BASH_REMATCH[1]}")
          fi
          echo "IMAGE_TAGS=${TAGS[*]}" >> $GITHUB_ENV

      - name: Build and publish image to Quay
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.context }}
          registry: quay.io
          repository: ${{ secrets.REGISTRY_NAMESPACE }}/${{ env.image_name }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          tags: ${{ env.IMAGE_TAGS }}
          
